### ISSUE TITLE
testServer?

### ISSUE THREAD

**Issue by tommck** [toddq/picobrewing#4]
I noticed in your code, you have config for a testServer.

Where is the code for this?

**Comment by toddq** [comment]
Hidden from public view, as it was never written for general consumption.  But since you asked I've zipped and attached it here.  Keep your expectations low ;).  Run with `ruby test_server.rb`.

[test_server.zip](https://github.com/toddq/whatspicobrewing/files/683508/test_server.zip)

**Comment by tommck** [comment]
Awesome.. will possibly be using it here: https://github.com/tommck/alexa-picobrew :)
