### ISSUE TITLE
PicoBrew APIs have changed

### ISSUE THREAD

**Issue by toddq** [toddq/picobrewing#5]
At the moment this app is completely broken, as PicoBrew has replaced the json apis with all new ones, as well as finally started requiring authentication to actually request data.  Both of these are actually good things, but will require some time to reverse engineer and document the new apis and move to using them.  Also, will need to add a login step.  The new apis look much more sane and readable than the old one though (except for using POST for all methods to simply get data).

**Comment by tommck** [comment]
That sucks.  means I'll need to redo my code too

**Comment by ryanmendoza** [comment]
Did you figure anything out with this? It looks like they’re using cookies to protect API resources... which is not sane, ha

**Comment by toddq** [comment]
@ryanmendoza Yeah, I wrote a Ruby library to front their "apis" (https://github.com/toddq/picobrew-api) and then a web proxy that uses it (https://github.com/toddq/pico-proxy) to give me a sane api to work with.  See the pico-proxy readme for more info.  And this webapp is now hosted along with the proxy on Heroku.
